//===----------------------------------------------------------------------===//
//
// mtxparse - MatrixDSL parser + AST dumper
//
// Owner: Vinay A (24BCB0131)
//
// Runs the full lexer -> parser pipeline over a .mtx file and prints the
// resulting AST, or reports every syntax error found (panic-mode recovery
// means a single missing semicolon produces one error, not a cascade).
//
// This is the Review 2 counterpart to mtxlex: where mtxlex proved the
// grammar's token specification executes, mtxparse proves the grammar's
// full production set does - the --dump-ast output is generated by the
// exact same DumpVisitor the parser test suite compares against.
//
// Usage:
//   mtxparse <file.mtx> [options]
//
// Options:
//   --quiet      suppress the banner
//
//===----------------------------------------------------------------------===//

#include "../../compiler/frontend/ast/AST.h"
#include "../../compiler/frontend/lexer/Lexer.h"
#include "../../compiler/frontend/parser/Parser.h"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

namespace {

void printUsage(const char *program) {
  std::printf("mtxparse - MatrixDSL parser and AST dumper\n\n");
  std::printf("Usage: %s <file.mtx> [options]\n\n", program);
  std::printf("Options:\n");
  std::printf("  --quiet      suppress the banner\n");
  std::printf("  -h, --help   this message\n");
}

bool readFile(const std::string &path, std::string &out) {
  std::ifstream in(path);
  if (!in)
    return false;
  std::ostringstream ss;
  ss << in.rdbuf();
  out = ss.str();
  return true;
}

} // namespace

int main(int argc, char **argv) {
  if (argc < 2) {
    printUsage(argv[0]);
    return 1;
  }

  std::string inputPath;
  bool quiet = false;

  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    if (arg == "-h" || arg == "--help") {
      printUsage(argv[0]);
      return 0;
    } else if (arg == "--quiet") {
      quiet = true;
    } else if (!arg.empty() && arg[0] == '-') {
      std::fprintf(stderr, "mtxparse: unknown option '%s'\n", arg.c_str());
      return 1;
    } else {
      inputPath = arg;
    }
  }

  if (inputPath.empty()) {
    std::fprintf(stderr, "mtxparse: no input file\n");
    return 1;
  }

  std::string source;
  if (!readFile(inputPath, source)) {
    std::fprintf(stderr, "mtxparse: cannot open '%s'\n", inputPath.c_str());
    return 1;
  }

  if (!quiet)
    std::printf("MatrixDSL Parser v1.0 - %s\n\n", inputPath.c_str());

  matrixdsl::Lexer lexer(source);
  std::vector<matrixdsl::Token> tokens = lexer.tokenize();

  if (lexer.hasErrors()) {
    std::fprintf(stderr, "%zu lexical error(s):\n", lexer.errors().size());
    for (const std::string &e : lexer.errors())
      std::fprintf(stderr, "  %s:%s\n", inputPath.c_str(), e.c_str());
    return 1;
  }

  matrixdsl::Parser parser(std::move(tokens));
  matrixdsl::ProgramPtr program = parser.parseProgram();

  if (parser.hasErrors()) {
    std::fprintf(stderr, "%zu syntax error(s):\n\n", parser.errors().size());
    for (const matrixdsl::ParseError &e : parser.errors())
      std::fprintf(stderr, "  %s\n", e.format(inputPath).c_str());
    return 1;
  }

  std::printf("%s", matrixdsl::dumpAST(*program).c_str());

  if (!quiet)
    std::printf("\n%zu statement(s) parsed, no errors.\n",
               program->statements.size());

  return 0;
}
